replicaCount: 1

image:
  registry: ""
  repository: arcana-api
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

env:
  PORT: "8080"
  POSTGRES_HOST: "postgres.arcana.svc.cluster.local"
  REDIS_HOST: "redis.arcana.svc.cluster.local"
  TEMPORAL_HOST: "temporal.arcana.svc.cluster.local"
  MINIO_HOST: "minio.arcana.svc.cluster.local"
  NATS_HOST: "nats.arcana.svc.cluster.local"

probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m
