apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ArcanaRequireResourceLimits
metadata:
  name: enforce-resource-limits
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["arcana"]
