apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ArcanaRequireSecurityContext
metadata:
  name: enforce-security-context
spec:
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces: ["arcana"]
