replicaCount: 2

image:
  registry: ""
  repository: localhost/arcana-operator
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8082

env:
  PORT: "8082"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.arcana.svc.cluster.local:4318"

probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m

rbac:
  create: true

pdb:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 75
  targetMemory: 80

tls:
  enabled: false
  secretName: arcana-service-tls
  mountPath: /etc/tls
