{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arcana-agui.serviceAccountName" . }}
  labels:
    {{- include "arcana-agui.labels" . | nindent 4 }}
{{- end }}
