replicaCount: 1

image:
  registry: ""
  repository: arcana-mesh
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8083

env:
  PORT: "8083"
  NATS_URL: "nats://nats.arcana.svc.cluster.local:4222"

probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m
