{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{{ include "arcana-annotate.serviceAccountName" . }}}
  labels:
    {{- include "arcana-annotate.labels" . | nindent 4 }}
{{- end }}
