replicaCount: 1

image:
  registry: ""
  repository: arcana-annotate
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8102

env:
  PORT: "8102"

probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m
