replicaCount: 1

image:
  registry: ""
  repository: arcana-studio
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 3000

env: {}

probes:
  liveness: "/"
  readiness: "/"

resources:
  requests:
    memory: 32Mi
    cpu: 25m
  limits:
    memory: 64Mi
    cpu: 100m
