{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "arcana-skills.serviceAccountName" . }}
  labels:
    {{- include "arcana-skills.labels" . | nindent 4 }}
{{- end }}
