replicaCount: 1

image:
  registry: ""
  repository: arcana-skills
  tag: dev
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8085

env:
  PORT: "8085"
  POSTGRES_HOST: "postgres.arcana.svc.cluster.local"
  REDIS_HOST: "redis.arcana.svc.cluster.local"

probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 64Mi
    cpu: 50m
  limits:
    memory: 128Mi
    cpu: 250m
