replicaCount: 1

image:
  registry: localhost:5001
  tag: "0.1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8085

env:
  PORT: "8085"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "arcana"
  POSTGRES_DB: "arcana"
  REDIS_URL: "redis://redis:6379"


probes:
  liveness: "/healthz"
  readiness: "/readyz"

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 500m
